### ISSUE TITLE
Lint job on scss files

### ISSUE THREAD

**Issue by archco** [archco/cosmos-css#132]
> https://github.com/brigade/scss-lint

린트 작업을 한다. 
- [x] `NameFormat`  - function, mixin을 `hyphenated_lowercase`로 통일한다. (kebab-case)
- [x] `NestingDepth` - nesting 단계가 깊은건 private mixin으로 따로 분리한다.
- [x] `SelectorDepth`
- [x] `IdSelector`

### The scss-lint rules that will ignored.
- Comment
- QualifyingElement - optional helper class로 사용할 것이다.
- ImportantRule - 소수지만 필요하다.

**Comment by archco** [comment]
.scss-lint.yml
```yml
linters:
  Comment:
    enabled: false
  QualifyingElement:
    enabled: false
  ImportantRule:
    enabled: false
  PropertySortOrder:
    order: recess

```
